name: Deploy to Server

on:
  push:
    branches: [main]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 创建项目目录
            mkdir -p /opt/final-lab
            cd /opt/final-lab
            
            # 克隆或更新仓库
            if [ -d ".git" ]; then
              git pull
            else
              git clone https://github.com/${{ github.repository }} .
            fi
            
            # 部署应用
            docker-compose down
            docker-compose up -d --build
            
            # 检查容器状态
            docker ps