version: '3.8'

services:
  # 个人网站服务
  personal_site:
    build: ./personal_site  # 指向包含 Dockerfile 和网站文件的目录
    container_name: personal-website
    ports:
      - "8081:80"  # 主机端口:容器端口
    restart: always
    networks:
      - app-network
    volumes:
      - ./personal_site:/usr/share/nginx/html:ro  # 开发时可挂载本地目录

  # Todo应用服务
  todo_app:
    build: ./todo_app  # 指向包含 Dockerfile 的目录
    container_name: todo-application
    ports:
      - "8082:80"  # 主机端口:容器端口
    restart: always
    networks:
      - app-network

# 创建网络让两个容器可以通信
networks:
  app-network:
    driver: bridge